<!DOCTYPE customer [
<!ELEMENT customers (customer+)>
<!ELEMENT customer (id,name,gender,phone,email,address)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
]>

<customers>
    <customer>
    <id>1</id>
    <name>NYAGORME HAPPYl</name>
    <gender> Female</gender>
    <phone>0512345678</phone>
    <email>someone.12@icloud.com</email>
    <address>T Town 11</address>
    </customer>
    <customer>
    <id>1</id>
    <name>ENOCH</name>
    <gender>Male</gender>
    <phone>0512345634</phone>
    <email>someone.12@icloud.com</email>
    <address>TWE 11</address>
    </customer>
    <customer>
    <id>1</id>
    <name>MAXWELL</name>
    <gender>Male</gender>
    <phone>05123238</phone>
    <email>sabby.12@icloud.com</email>
    <address>T  11</address>
    </customer>
     <customer>
    <id>1</id>
    <name>ENOCH</name>
    <gender>Male</gender>
    <phone>0512345634</phone>
    <email>someone.12@icloud.com</email>
    <address>TWE 11</address>
    </customer>
     <customer>
    <id>1</id>
    <name>ENOCH</name>
    <gender>Male</gender>
    <phone>0512345634</phone>
    <email>omeone.12@icloud.com</email>
    <address>TWE 11</address>
    </customer>
     <customer>
    <id>1</id>
    <name>ENOCH</name>
    <gender>Male</gender>
    <phone>0512345634</phone>
    <email>someone.12@icloud.com</email>
    <address>TWE 11</address>
    </customer>
</customers>